# Generated by Django 4.1.7 on 2023-04-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
