# Generated by Django 4.1.7 on 2023-04-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Что-то под Наши работы',
                'ordering': ['-id'],
            },
        ),
    ]
