# Generated by Django 4.1.7 on 2023-04-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='Название сайта')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('help_text', models.CharField(max_length=100, verbose_name='Хэлпер текст')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
        migrations.CreateModel(
            name='LinkOfPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('icon', models.FileField(upload_to='%Y/%m/%d/', verbose_name='Иконка')),
                ('main_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pageinfo.mainpageinfo', verbose_name='Информация о сайте')),
                ('main_page_info_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pageinfo.mainpageinfo', verbose_name='Информация о сайте')),
                ('main_page_info_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pageinfo.mainpageinfo', verbose_name='Информация о сайте')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
