# Generated by Django 4.1.7 on 2023-04-07 05:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/%d/', verbose_name='Изображения')),
                ('project_info', ckeditor.fields.RichTextField(verbose_name='Информация о проекте')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=200)),
                ('channel_chat_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Telegram Bot Settings',
                'verbose_name_plural': 'Telegram Bot Settings',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=15, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/%d/', verbose_name='Изображения')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
