# Generated by Django 4.1.7 on 2023-04-07 05:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='project_info_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Информация о проекте'),
        ),
        migrations.AddField(
            model_name='article',
            name='project_info_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Информация о проекте'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='review',
            name='article_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article'),
        ),
        migrations.AddField(
            model_name='review',
            name='article_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_en',
            field=models.CharField(max_length=15, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_ru',
            field=models.CharField(max_length=15, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_en',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
